package ru.pearx.pmdumper

import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent
import net.minecraftforge.fml.common.event.FMLServerStartingEvent
import java.io.File

@Mod(modLanguageAdapter = "net.shadowfacts.forgelin.KotlinAdapter", name = NAME, modid = ID, version = VERSION, acceptedMinecraftVersions = ACCEPTED_MINECRAFT_VERSIONS, acceptableRemoteVersions = "*", dependencies = DEPENDENCIES)
object PMDumper {
    lateinit var dumpersDirectory: File private set

    @Mod.EventHandler
    fun preInit(event: FMLPreInitializationEvent) {
        dumpersDirectory = File(event.modConfigurationDirectory.parentFile, ID)
        with(event.modMetadata) {
            autogenerated = false
            modId = ID
            name = NAME
            description = DESCRIPTION
            version = VERSION
            authorList = AUTHORS
        }
    }

    @Mod.EventHandler
    fun serverStart(event: FMLServerStartingEvent) {
        event.registerServerCommand(PMDumperCommand())
    }
}