package ru.pearx.pmdumper;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.Logger;
import ru.pearx.pmdumper.dumpers.*;
import ru.pearx.pmdumper.dumpers.base.IDumper;

import java.text.SimpleDateFormat;
import java.util.*;

/**
 * Created by mrAppleXZ on 11.06.17 12:27.
 */
@Mod(modid = PMDumper.ID, name = PMDumper.NAME, version = PMDumper.VERSION, acceptedMinecraftVersions = "", clientSideOnly = true)
public class PMDumper
{
    @Mod.Instance
    public static PMDumper INSTANCE;

    public static final String ID = "pmdumper";
    public static final String NAME = "PM Dumper";
    public static final String VERSION = "@VERSION@";

    @SideOnly(Side.CLIENT)
    public List<IDumper> dumps = new ArrayList<>();
    public Logger log;

    @Mod.EventHandler
    @SideOnly(Side.CLIENT)
    public void serverStart(FMLServerStartingEvent e)
    {
        dumps.add(new DumperItems());
        dumps.add(new DumperCapabilities());
        dumps.add(new DumperSounds());
        dumps.add(new DumperEnchantments());
        dumps.add(new DumperModels());
        dumps.add(new DumperBlocks());
        dumps.add(new DumperEntities());
        dumps.add(new DumperLootTables());
        dumps.add(new DumperVillagerProfessions());
        dumps.add(new DumperBiomes());
        dumps.add(new DumperPotions());
        dumps.add(new DumperAdvancements());
        e.registerServerCommand(new PMDCommand());
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        log = e.getModLog();
        ModMetadata md = e.getModMetadata();
        md.name = NAME;
        md.modId = ID;
        md.version = VERSION;
        md.description = "Dump (almost) all the things!";
        md.autogenerated = false;
        md.authorList = Collections.singletonList("mrAppleXZ");
        md.url = "https://minecraft.curseforge.com/projects/pm-dumper";
    }

    public static String getCurrentDate()
    {
        SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd-kk-mm");
        return form.format(new Date());
    }
}
